name: ci-cd pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-images .

      - name: Show Docker images
        run: docker images